# Generated by Django 4.1.4 on 2022-12-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('task_title', models.CharField(max_length=255)),
                ('parent_task_id', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=1000)),
                ('target_date', models.DateTimeField(null=True)),
                ('priority', models.IntegerField(default=0)),
                ('note', models.CharField(max_length=1000, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.task_category')),
                ('person_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.person')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.task_status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.task_type')),
            ],
        ),
    ]
