# Generated by Django 4.1.4 on 2022-12-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimate_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='spent_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task_category',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='main.project'),
            preserve_default=False,
        ),
    ]
