# Generated by Django 4.1.4 on 2022-12-13 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_estimate_time_task_spent_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.task'),
        ),
    ]
