# Generated by Django 4.1.4 on 2022-12-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_task_parent_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LogTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spent_time', models.FloatField(default=0)),
                ('comments', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.activity')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.person')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.task')),
            ],
        ),
    ]
