# Generated by Django 4.1.4 on 2022-12-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_activity_logtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='spent_time',
            field=models.FloatField(default=0),
        ),
    ]
