# Generated by Django 4.1.4 on 2022-12-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_spent_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='task',
            name='estimate_time',
            field=models.FloatField(null=True),
        ),
    ]
