# Generated by Django 4.1.4 on 2022-12-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_task_task_id_alter_task_estimate_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtime',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='logtime',
            name='updated_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_date',
            field=models.DateTimeField(),
        ),
    ]
