# Generated by Django 4.1.4 on 2022-12-18 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_logtime_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='person_in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.person'),
        ),
    ]
